version: "3.9"
services:
  
  golang-app:
    build: ./backend
    container_name: golang-server
    ports:
      - "8082:8081"
    links: 
      - redis
    depends_on: 
      - redis        
  redis:
    image: "redis:latest"
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes: 
      - ./redis.conf:/usr/local/etc/redis/redis.conf     
