version: "3.9"
services:
  
  todo-app:
    build: ./backend
    container_name: todo-go-server
    ports:
      - "8082:8081"
    links: 
      - redis
    depends_on: 
      - redis        
  redis:
    image: "redis:latest"
    container_name: todo-redis-server
    ports:
      - "6379:6379"
    volumes: 
      - ./redis.conf:/usr/local/etc/redis/redis.conf     
  ui:
    build: ./frontend
    container_name: todo-ui
    ports: 
      - "4200:80"
    links: 
      - todo-app
